// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: inventory/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// a list of given events
	Given []*anypb.Any `protobuf:"bytes,1,rep,name=given,proto3" json:"given,omitempty"`
	// request that we are testing
	When *anypb.Any `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
}

func (x *SpecRequest) Reset() {
	*x = SpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecRequest) ProtoMessage() {}

func (x *SpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecRequest.ProtoReflect.Descriptor instead.
func (*SpecRequest) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *SpecRequest) GetGiven() []*anypb.Any {
	if x != nil {
		return x.Given
	}
	return nil
}

func (x *SpecRequest) GetWhen() *anypb.Any {
	if x != nil {
		return x.When
	}
	return nil
}

type SpecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// actual response. Must be nil on error
	Response *anypb.Any `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// list of events that were produced by the aggregate
	Events []*anypb.Any `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// status code maps to [google.rpc.Code][google.rpc.Code]
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// logical error in english
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SpecResponse) Reset() {
	*x = SpecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecResponse) ProtoMessage() {}

func (x *SpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecResponse.ProtoReflect.Descriptor instead.
func (*SpecResponse) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *SpecResponse) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SpecResponse) GetEvents() []*anypb.Any {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SpecResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SpecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AboutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AboutRequest) Reset() {
	*x = AboutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AboutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AboutRequest) ProtoMessage() {}

func (x *AboutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AboutRequest.ProtoReflect.Descriptor instead.
func (*AboutRequest) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{2}
}

type AboutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author  string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Detail  string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Contact string `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
}

func (x *AboutResponse) Reset() {
	*x = AboutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AboutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AboutResponse) ProtoMessage() {}

func (x *AboutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AboutResponse.ProtoReflect.Descriptor instead.
func (*AboutResponse) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *AboutResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AboutResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AboutResponse) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

// locations are nested and could be bulk-added
type AddLocationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locs []*AddLocationsReq_Loc `protobuf:"bytes,1,rep,name=locs,proto3" json:"locs,omitempty"`
	// UID of a parent location
	Parent string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *AddLocationsReq) Reset() {
	*x = AddLocationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLocationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocationsReq) ProtoMessage() {}

func (x *AddLocationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocationsReq.ProtoReflect.Descriptor instead.
func (*AddLocationsReq) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *AddLocationsReq) GetLocs() []*AddLocationsReq_Loc {
	if x != nil {
		return x.Locs
	}
	return nil
}

func (x *AddLocationsReq) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type AddLocationsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locs []*AddLocationsResp_Loc `protobuf:"bytes,1,rep,name=locs,proto3" json:"locs,omitempty"`
}

func (x *AddLocationsResp) Reset() {
	*x = AddLocationsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLocationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocationsResp) ProtoMessage() {}

func (x *AddLocationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocationsResp.ProtoReflect.Descriptor instead.
func (*AddLocationsResp) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *AddLocationsResp) GetLocs() []*AddLocationsResp_Loc {
	if x != nil {
		return x.Locs
	}
	return nil
}

type LocationAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` //LocType type = 3;
	// added later
	Parent string `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *LocationAdded) Reset() {
	*x = LocationAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationAdded) ProtoMessage() {}

func (x *LocationAdded) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationAdded.ProtoReflect.Descriptor instead.
func (*LocationAdded) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *LocationAdded) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LocationAdded) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocationAdded) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type LocationMoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OldParent string `protobuf:"bytes,2,opt,name=oldParent,proto3" json:"oldParent,omitempty"`
	NewParent string `protobuf:"bytes,3,opt,name=newParent,proto3" json:"newParent,omitempty"`
}

func (x *LocationMoved) Reset() {
	*x = LocationMoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationMoved) ProtoMessage() {}

func (x *LocationMoved) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationMoved.ProtoReflect.Descriptor instead.
func (*LocationMoved) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *LocationMoved) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LocationMoved) GetOldParent() string {
	if x != nil {
		return x.OldParent
	}
	return ""
}

func (x *LocationMoved) GetNewParent() string {
	if x != nil {
		return x.NewParent
	}
	return ""
}

type MoveLocationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NewParent string `protobuf:"bytes,2,opt,name=newParent,proto3" json:"newParent,omitempty"`
}

func (x *MoveLocationReq) Reset() {
	*x = MoveLocationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveLocationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveLocationReq) ProtoMessage() {}

func (x *MoveLocationReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveLocationReq.ProtoReflect.Descriptor instead.
func (*MoveLocationReq) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{8}
}

func (x *MoveLocationReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MoveLocationReq) GetNewParent() string {
	if x != nil {
		return x.NewParent
	}
	return ""
}

type MoveLocationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveLocationResp) Reset() {
	*x = MoveLocationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveLocationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveLocationResp) ProtoMessage() {}

func (x *MoveLocationResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveLocationResp.ProtoReflect.Descriptor instead.
func (*MoveLocationResp) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{9}
}

type AddProductsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skus []string `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
}

func (x *AddProductsReq) Reset() {
	*x = AddProductsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsReq) ProtoMessage() {}

func (x *AddProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsReq.ProtoReflect.Descriptor instead.
func (*AddProductsReq) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{10}
}

func (x *AddProductsReq) GetSkus() []string {
	if x != nil {
		return x.Skus
	}
	return nil
}

type AddProductsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []string `protobuf:"bytes,2,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *AddProductsResp) Reset() {
	*x = AddProductsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsResp) ProtoMessage() {}

func (x *AddProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsResp.ProtoReflect.Descriptor instead.
func (*AddProductsResp) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{11}
}

func (x *AddProductsResp) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type ProductAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Sku string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
}

func (x *ProductAdded) Reset() {
	*x = ProductAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAdded) ProtoMessage() {}

func (x *ProductAdded) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAdded.ProtoReflect.Descriptor instead.
func (*ProductAdded) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{12}
}

func (x *ProductAdded) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ProductAdded) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type UpdateInventoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location     string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Product      string `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	OnHandChange int64  `protobuf:"varint,3,opt,name=OnHandChange,proto3" json:"OnHandChange,omitempty"`
}

func (x *UpdateInventoryReq) Reset() {
	*x = UpdateInventoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryReq) ProtoMessage() {}

func (x *UpdateInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryReq.ProtoReflect.Descriptor instead.
func (*UpdateInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateInventoryReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateInventoryReq) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *UpdateInventoryReq) GetOnHandChange() int64 {
	if x != nil {
		return x.OnHandChange
	}
	return 0
}

type UpdateInventoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OnHand int64 `protobuf:"varint,1,opt,name=OnHand,proto3" json:"OnHand,omitempty"`
}

func (x *UpdateInventoryResp) Reset() {
	*x = UpdateInventoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryResp) ProtoMessage() {}

func (x *UpdateInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryResp.ProtoReflect.Descriptor instead.
func (*UpdateInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateInventoryResp) GetOnHand() int64 {
	if x != nil {
		return x.OnHand
	}
	return 0
}

type InventoryUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location     string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Product      string `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	OnHandChange int64  `protobuf:"varint,3,opt,name=OnHandChange,proto3" json:"OnHandChange,omitempty"`
	OnHand       int64  `protobuf:"varint,4,opt,name=OnHand,proto3" json:"OnHand,omitempty"`
}

func (x *InventoryUpdated) Reset() {
	*x = InventoryUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUpdated) ProtoMessage() {}

func (x *InventoryUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUpdated.ProtoReflect.Descriptor instead.
func (*InventoryUpdated) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{15}
}

func (x *InventoryUpdated) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *InventoryUpdated) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *InventoryUpdated) GetOnHandChange() int64 {
	if x != nil {
		return x.OnHandChange
	}
	return 0
}

func (x *InventoryUpdated) GetOnHand() int64 {
	if x != nil {
		return x.OnHand
	}
	return 0
}

type ListLocationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *ListLocationsReq) Reset() {
	*x = ListLocationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLocationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsReq) ProtoMessage() {}

func (x *ListLocationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsReq.ProtoReflect.Descriptor instead.
func (*ListLocationsReq) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{16}
}

func (x *ListLocationsReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ListLocationsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locs []*ListLocationsResp_Loc `protobuf:"bytes,1,rep,name=locs,proto3" json:"locs,omitempty"`
}

func (x *ListLocationsResp) Reset() {
	*x = ListLocationsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLocationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResp) ProtoMessage() {}

func (x *ListLocationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResp.ProtoReflect.Descriptor instead.
func (*ListLocationsResp) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{17}
}

func (x *ListLocationsResp) GetLocs() []*ListLocationsResp_Loc {
	if x != nil {
		return x.Locs
	}
	return nil
}

type GetLocInventoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetLocInventoryReq) Reset() {
	*x = GetLocInventoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocInventoryReq) ProtoMessage() {}

func (x *GetLocInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocInventoryReq.ProtoReflect.Descriptor instead.
func (*GetLocInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{18}
}

func (x *GetLocInventoryReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// this counts nested locations
type GetLocInventoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GetLocInventoryResp_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetLocInventoryResp) Reset() {
	*x = GetLocInventoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocInventoryResp) ProtoMessage() {}

func (x *GetLocInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocInventoryResp.ProtoReflect.Descriptor instead.
func (*GetLocInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{19}
}

func (x *GetLocInventoryResp) GetItems() []*GetLocInventoryResp_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reservation string             `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Items       []*ReserveReq_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Tags        map[string]string  `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Location    string             `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *ReserveReq) Reset() {
	*x = ReserveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveReq) ProtoMessage() {}

func (x *ReserveReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveReq.ProtoReflect.Descriptor instead.
func (*ReserveReq) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{20}
}

func (x *ReserveReq) GetReservation() string {
	if x != nil {
		return x.Reservation
	}
	return ""
}

func (x *ReserveReq) GetItems() []*ReserveReq_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveReq) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ReserveReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ReserveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reservation string `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
}

func (x *ReserveResp) Reset() {
	*x = ReserveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResp) ProtoMessage() {}

func (x *ReserveResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResp.ProtoReflect.Descriptor instead.
func (*ReserveResp) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{21}
}

func (x *ReserveResp) GetReservation() string {
	if x != nil {
		return x.Reservation
	}
	return ""
}

type Reserved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reservation string           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Code        string           `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Items       []*Reserved_Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Reserved) Reset() {
	*x = Reserved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserved) ProtoMessage() {}

func (x *Reserved) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserved.ProtoReflect.Descriptor instead.
func (*Reserved) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{22}
}

func (x *Reserved) GetReservation() string {
	if x != nil {
		return x.Reservation
	}
	return ""
}

func (x *Reserved) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Reserved) GetItems() []*Reserved_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type FulfillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reservation string             `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Items       []*FulfillReq_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *FulfillReq) Reset() {
	*x = FulfillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FulfillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillReq) ProtoMessage() {}

func (x *FulfillReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillReq.ProtoReflect.Descriptor instead.
func (*FulfillReq) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{23}
}

func (x *FulfillReq) GetReservation() string {
	if x != nil {
		return x.Reservation
	}
	return ""
}

func (x *FulfillReq) GetItems() []*FulfillReq_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type FulfillResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FulfillResp) Reset() {
	*x = FulfillResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FulfillResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillResp) ProtoMessage() {}

func (x *FulfillResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillResp.ProtoReflect.Descriptor instead.
func (*FulfillResp) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{24}
}

type Fulfilled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reservation string            `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Items       []*Fulfilled_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Fulfilled) Reset() {
	*x = Fulfilled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fulfilled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fulfilled) ProtoMessage() {}

func (x *Fulfilled) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fulfilled.ProtoReflect.Descriptor instead.
func (*Fulfilled) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{25}
}

func (x *Fulfilled) GetReservation() string {
	if x != nil {
		return x.Reservation
	}
	return ""
}

func (x *Fulfilled) GetItems() []*Fulfilled_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Cancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reservation string            `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Items       []*Cancelled_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Cancelled) Reset() {
	*x = Cancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancelled) ProtoMessage() {}

func (x *Cancelled) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancelled.ProtoReflect.Descriptor instead.
func (*Cancelled) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{26}
}

func (x *Cancelled) GetReservation() string {
	if x != nil {
		return x.Reservation
	}
	return ""
}

func (x *Cancelled) GetItems() []*Cancelled_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddLocationsReq_Loc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Locs []*AddLocationsReq_Loc `protobuf:"bytes,4,rep,name=locs,proto3" json:"locs,omitempty"`
}

func (x *AddLocationsReq_Loc) Reset() {
	*x = AddLocationsReq_Loc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLocationsReq_Loc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocationsReq_Loc) ProtoMessage() {}

func (x *AddLocationsReq_Loc) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocationsReq_Loc.ProtoReflect.Descriptor instead.
func (*AddLocationsReq_Loc) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AddLocationsReq_Loc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddLocationsReq_Loc) GetLocs() []*AddLocationsReq_Loc {
	if x != nil {
		return x.Locs
	}
	return nil
}

type AddLocationsResp_Loc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid    string                  `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Parent string                  `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Locs   []*AddLocationsResp_Loc `protobuf:"bytes,4,rep,name=locs,proto3" json:"locs,omitempty"`
}

func (x *AddLocationsResp_Loc) Reset() {
	*x = AddLocationsResp_Loc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLocationsResp_Loc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocationsResp_Loc) ProtoMessage() {}

func (x *AddLocationsResp_Loc) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocationsResp_Loc.ProtoReflect.Descriptor instead.
func (*AddLocationsResp_Loc) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *AddLocationsResp_Loc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddLocationsResp_Loc) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AddLocationsResp_Loc) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *AddLocationsResp_Loc) GetLocs() []*AddLocationsResp_Loc {
	if x != nil {
		return x.Locs
	}
	return nil
}

type ListLocationsResp_Loc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// LocType type = 2;
	Uid     string                   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Parent  string                   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Chidren []*ListLocationsResp_Loc `protobuf:"bytes,5,rep,name=chidren,proto3" json:"chidren,omitempty"`
}

func (x *ListLocationsResp_Loc) Reset() {
	*x = ListLocationsResp_Loc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLocationsResp_Loc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResp_Loc) ProtoMessage() {}

func (x *ListLocationsResp_Loc) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResp_Loc.ProtoReflect.Descriptor instead.
func (*ListLocationsResp_Loc) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{17, 0}
}

func (x *ListLocationsResp_Loc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListLocationsResp_Loc) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ListLocationsResp_Loc) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListLocationsResp_Loc) GetChidren() []*ListLocationsResp_Loc {
	if x != nil {
		return x.Chidren
	}
	return nil
}

type GetLocInventoryResp_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product   string `protobuf:"bytes,1,opt,name=Product,proto3" json:"Product,omitempty"`
	OnHand    int64  `protobuf:"varint,2,opt,name=OnHand,proto3" json:"OnHand,omitempty"`
	Available int64  `protobuf:"varint,3,opt,name=Available,proto3" json:"Available,omitempty"`
}

func (x *GetLocInventoryResp_Item) Reset() {
	*x = GetLocInventoryResp_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocInventoryResp_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocInventoryResp_Item) ProtoMessage() {}

func (x *GetLocInventoryResp_Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocInventoryResp_Item.ProtoReflect.Descriptor instead.
func (*GetLocInventoryResp_Item) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{19, 0}
}

func (x *GetLocInventoryResp_Item) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *GetLocInventoryResp_Item) GetOnHand() int64 {
	if x != nil {
		return x.OnHand
	}
	return 0
}

func (x *GetLocInventoryResp_Item) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type ReserveReq_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku      string `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *ReserveReq_Item) Reset() {
	*x = ReserveReq_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveReq_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveReq_Item) ProtoMessage() {}

func (x *ReserveReq_Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveReq_Item.ProtoReflect.Descriptor instead.
func (*ReserveReq_Item) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{20, 0}
}

func (x *ReserveReq_Item) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ReserveReq_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Reserved_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product  string `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *Reserved_Item) Reset() {
	*x = Reserved_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reserved_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserved_Item) ProtoMessage() {}

func (x *Reserved_Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserved_Item.ProtoReflect.Descriptor instead.
func (*Reserved_Item) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{22, 0}
}

func (x *Reserved_Item) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Reserved_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Reserved_Item) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type FulfillReq_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product  string `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *FulfillReq_Item) Reset() {
	*x = FulfillReq_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FulfillReq_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillReq_Item) ProtoMessage() {}

func (x *FulfillReq_Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillReq_Item.ProtoReflect.Descriptor instead.
func (*FulfillReq_Item) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{23, 0}
}

func (x *FulfillReq_Item) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *FulfillReq_Item) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *FulfillReq_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Fulfilled_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product  string `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Removed  int64  `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	OnHand   int64  `protobuf:"varint,4,opt,name=onHand,proto3" json:"onHand,omitempty"`
}

func (x *Fulfilled_Item) Reset() {
	*x = Fulfilled_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fulfilled_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fulfilled_Item) ProtoMessage() {}

func (x *Fulfilled_Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fulfilled_Item.ProtoReflect.Descriptor instead.
func (*Fulfilled_Item) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{25, 0}
}

func (x *Fulfilled_Item) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Fulfilled_Item) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Fulfilled_Item) GetRemoved() int64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

func (x *Fulfilled_Item) GetOnHand() int64 {
	if x != nil {
		return x.OnHand
	}
	return 0
}

type Cancelled_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product  string `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Released int64  `protobuf:"varint,3,opt,name=released,proto3" json:"released,omitempty"`
}

func (x *Cancelled_Item) Reset() {
	*x = Cancelled_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_api_api_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cancelled_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancelled_Item) ProtoMessage() {}

func (x *Cancelled_Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_api_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancelled_Item.ProtoReflect.Descriptor instead.
func (*Cancelled_Item) Descriptor() ([]byte, []int) {
	return file_inventory_api_api_proto_rawDescGZIP(), []int{26, 0}
}

func (x *Cancelled_Item) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Cancelled_Item) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Cancelled_Item) GetReleased() int64 {
	if x != nil {
		return x.Released
	}
	return 0
}

var File_inventory_api_api_proto protoreflect.FileDescriptor

var file_inventory_api_api_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0b,
	0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x67,
	0x69, 0x76, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x05, 0x67, 0x69, 0x76, 0x65, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x77, 0x68, 0x65,
	0x6e, 0x22, 0x9c, 0x01, 0x0a, 0x0c, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x0e, 0x0a, 0x0c, 0x41, 0x62, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x59, 0x0a, 0x0d, 0x41, 0x62, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x2f, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x4c, 0x6f, 0x63, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x1a, 0x4a, 0x0a, 0x03, 0x4c, 0x6f, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x4c, 0x6f, 0x63, 0x52, 0x04,
	0x6c, 0x6f, 0x63, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x6f, 0x63,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x4c, 0x6f, 0x63, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x73, 0x1a, 0x75, 0x0a, 0x03, 0x4c,
	0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x30, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4c, 0x6f, 0x63, 0x52, 0x04, 0x6c, 0x6f,
	0x63, 0x73, 0x22, 0x4d, 0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64,
	0x64, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x22, 0x5d, 0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x76,
	0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x6c, 0x64, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x6c, 0x64, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x22, 0x41, 0x0a, 0x0f, 0x4d, 0x6f, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x4d, 0x6f, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x24, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6b, 0x75, 0x73, 0x22, 0x25, 0x0a,
	0x0f, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x22, 0x32, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x64, 0x64, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x22, 0x6e, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x4f, 0x6e, 0x48, 0x61,
	0x6e, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x2d, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x4f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x4f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x4f, 0x6e, 0x48, 0x61, 0x6e, 0x64,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x6e, 0x48, 0x61, 0x6e, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x22, 0x2e,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc4,
	0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4c, 0x6f,
	0x63, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x73, 0x1a, 0x7c, 0x0a, 0x03, 0x4c, 0x6f, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x07,
	0x63, 0x68, 0x69, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4c, 0x6f, 0x63, 0x52, 0x07, 0x63, 0x68,
	0x69, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x30, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x49,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa5, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c,
	0x6f, 0x63, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x36, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x56, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x6e, 0x48,
	0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4f, 0x6e, 0x48, 0x61, 0x6e,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22,
	0x9a, 0x02, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x30, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x34, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x1a, 0x37, 0x0a, 0x09, 0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2f, 0x0a, 0x0b,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc7, 0x01,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x64, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x58, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb7, 0x01, 0x0a, 0x0a, 0x46, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x58, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0x0d, 0x0a, 0x0b, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x22, 0xcb, 0x01, 0x0a, 0x09, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c,
	0x65, 0x64, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x6e,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x48, 0x61, 0x6e, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x22, 0xb5,
	0x01, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x58, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x32, 0x76, 0x0a, 0x0b, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x41, 0x62, 0x6f, 0x75, 0x74, 0x12, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x62, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x62,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9e,
	0x04, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41,
	0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0c,
	0x4d, 0x6f, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x4a, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4a, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x63, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x07, 0x46,
	0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x12, 0x5a, 0x10, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x2d, 0x66, 0x72, 0x69, 0x64, 0x61, 0x79, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inventory_api_api_proto_rawDescOnce sync.Once
	file_inventory_api_api_proto_rawDescData = file_inventory_api_api_proto_rawDesc
)

func file_inventory_api_api_proto_rawDescGZIP() []byte {
	file_inventory_api_api_proto_rawDescOnce.Do(func() {
		file_inventory_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_inventory_api_api_proto_rawDescData)
	})
	return file_inventory_api_api_proto_rawDescData
}

var file_inventory_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_inventory_api_api_proto_goTypes = []interface{}{
	(*SpecRequest)(nil),              // 0: protos.SpecRequest
	(*SpecResponse)(nil),             // 1: protos.SpecResponse
	(*AboutRequest)(nil),             // 2: protos.AboutRequest
	(*AboutResponse)(nil),            // 3: protos.AboutResponse
	(*AddLocationsReq)(nil),          // 4: protos.AddLocationsReq
	(*AddLocationsResp)(nil),         // 5: protos.AddLocationsResp
	(*LocationAdded)(nil),            // 6: protos.LocationAdded
	(*LocationMoved)(nil),            // 7: protos.LocationMoved
	(*MoveLocationReq)(nil),          // 8: protos.MoveLocationReq
	(*MoveLocationResp)(nil),         // 9: protos.MoveLocationResp
	(*AddProductsReq)(nil),           // 10: protos.AddProductsReq
	(*AddProductsResp)(nil),          // 11: protos.AddProductsResp
	(*ProductAdded)(nil),             // 12: protos.ProductAdded
	(*UpdateInventoryReq)(nil),       // 13: protos.UpdateInventoryReq
	(*UpdateInventoryResp)(nil),      // 14: protos.UpdateInventoryResp
	(*InventoryUpdated)(nil),         // 15: protos.InventoryUpdated
	(*ListLocationsReq)(nil),         // 16: protos.ListLocationsReq
	(*ListLocationsResp)(nil),        // 17: protos.ListLocationsResp
	(*GetLocInventoryReq)(nil),       // 18: protos.GetLocInventoryReq
	(*GetLocInventoryResp)(nil),      // 19: protos.GetLocInventoryResp
	(*ReserveReq)(nil),               // 20: protos.ReserveReq
	(*ReserveResp)(nil),              // 21: protos.ReserveResp
	(*Reserved)(nil),                 // 22: protos.Reserved
	(*FulfillReq)(nil),               // 23: protos.FulfillReq
	(*FulfillResp)(nil),              // 24: protos.FulfillResp
	(*Fulfilled)(nil),                // 25: protos.Fulfilled
	(*Cancelled)(nil),                // 26: protos.Cancelled
	(*AddLocationsReq_Loc)(nil),      // 27: protos.AddLocationsReq.Loc
	(*AddLocationsResp_Loc)(nil),     // 28: protos.AddLocationsResp.Loc
	(*ListLocationsResp_Loc)(nil),    // 29: protos.ListLocationsResp.Loc
	(*GetLocInventoryResp_Item)(nil), // 30: protos.GetLocInventoryResp.Item
	(*ReserveReq_Item)(nil),          // 31: protos.ReserveReq.Item
	nil,                              // 32: protos.ReserveReq.TagsEntry
	(*Reserved_Item)(nil),            // 33: protos.Reserved.Item
	(*FulfillReq_Item)(nil),          // 34: protos.FulfillReq.Item
	(*Fulfilled_Item)(nil),           // 35: protos.Fulfilled.Item
	(*Cancelled_Item)(nil),           // 36: protos.Cancelled.Item
	(*anypb.Any)(nil),                // 37: google.protobuf.Any
}
var file_inventory_api_api_proto_depIdxs = []int32{
	37, // 0: protos.SpecRequest.given:type_name -> google.protobuf.Any
	37, // 1: protos.SpecRequest.when:type_name -> google.protobuf.Any
	37, // 2: protos.SpecResponse.response:type_name -> google.protobuf.Any
	37, // 3: protos.SpecResponse.events:type_name -> google.protobuf.Any
	27, // 4: protos.AddLocationsReq.locs:type_name -> protos.AddLocationsReq.Loc
	28, // 5: protos.AddLocationsResp.locs:type_name -> protos.AddLocationsResp.Loc
	29, // 6: protos.ListLocationsResp.locs:type_name -> protos.ListLocationsResp.Loc
	30, // 7: protos.GetLocInventoryResp.items:type_name -> protos.GetLocInventoryResp.Item
	31, // 8: protos.ReserveReq.items:type_name -> protos.ReserveReq.Item
	32, // 9: protos.ReserveReq.tags:type_name -> protos.ReserveReq.TagsEntry
	33, // 10: protos.Reserved.items:type_name -> protos.Reserved.Item
	34, // 11: protos.FulfillReq.items:type_name -> protos.FulfillReq.Item
	35, // 12: protos.Fulfilled.items:type_name -> protos.Fulfilled.Item
	36, // 13: protos.Cancelled.items:type_name -> protos.Cancelled.Item
	27, // 14: protos.AddLocationsReq.Loc.locs:type_name -> protos.AddLocationsReq.Loc
	28, // 15: protos.AddLocationsResp.Loc.locs:type_name -> protos.AddLocationsResp.Loc
	29, // 16: protos.ListLocationsResp.Loc.chidren:type_name -> protos.ListLocationsResp.Loc
	2,  // 17: protos.SpecService.About:input_type -> protos.AboutRequest
	0,  // 18: protos.SpecService.Spec:input_type -> protos.SpecRequest
	4,  // 19: protos.InventoryService.AddLocations:input_type -> protos.AddLocationsReq
	10, // 20: protos.InventoryService.AddProducts:input_type -> protos.AddProductsReq
	16, // 21: protos.InventoryService.ListLocations:input_type -> protos.ListLocationsReq
	8,  // 22: protos.InventoryService.MoveLocation:input_type -> protos.MoveLocationReq
	13, // 23: protos.InventoryService.UpdateInventory:input_type -> protos.UpdateInventoryReq
	18, // 24: protos.InventoryService.GetLocInventory:input_type -> protos.GetLocInventoryReq
	20, // 25: protos.InventoryService.Reserve:input_type -> protos.ReserveReq
	23, // 26: protos.InventoryService.Fulfill:input_type -> protos.FulfillReq
	3,  // 27: protos.SpecService.About:output_type -> protos.AboutResponse
	1,  // 28: protos.SpecService.Spec:output_type -> protos.SpecResponse
	5,  // 29: protos.InventoryService.AddLocations:output_type -> protos.AddLocationsResp
	11, // 30: protos.InventoryService.AddProducts:output_type -> protos.AddProductsResp
	17, // 31: protos.InventoryService.ListLocations:output_type -> protos.ListLocationsResp
	9,  // 32: protos.InventoryService.MoveLocation:output_type -> protos.MoveLocationResp
	14, // 33: protos.InventoryService.UpdateInventory:output_type -> protos.UpdateInventoryResp
	19, // 34: protos.InventoryService.GetLocInventory:output_type -> protos.GetLocInventoryResp
	21, // 35: protos.InventoryService.Reserve:output_type -> protos.ReserveResp
	24, // 36: protos.InventoryService.Fulfill:output_type -> protos.FulfillResp
	27, // [27:37] is the sub-list for method output_type
	17, // [17:27] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_inventory_api_api_proto_init() }
func file_inventory_api_api_proto_init() {
	if File_inventory_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inventory_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AboutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AboutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLocationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLocationsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationMoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveLocationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveLocationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInventoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInventoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLocationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLocationsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocInventoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocInventoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reserved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FulfillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FulfillResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fulfilled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLocationsReq_Loc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLocationsResp_Loc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLocationsResp_Loc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocInventoryResp_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveReq_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reserved_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FulfillReq_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fulfilled_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_api_api_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cancelled_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inventory_api_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_inventory_api_api_proto_goTypes,
		DependencyIndexes: file_inventory_api_api_proto_depIdxs,
		MessageInfos:      file_inventory_api_api_proto_msgTypes,
	}.Build()
	File_inventory_api_api_proto = out.File
	file_inventory_api_api_proto_rawDesc = nil
	file_inventory_api_api_proto_goTypes = nil
	file_inventory_api_api_proto_depIdxs = nil
}
