// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: seq/test.proto

package seq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_seq_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_seq_test_proto_rawDescGZIP(), []int{0}
}

type Simple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I32  int32  `protobuf:"varint,1,opt,name=I32,proto3" json:"I32,omitempty"`
	I64  int64  `protobuf:"varint,2,opt,name=I64,proto3" json:"I64,omitempty"`
	U32  uint32 `protobuf:"varint,3,opt,name=U32,proto3" json:"U32,omitempty"`
	U64  uint64 `protobuf:"varint,4,opt,name=U64,proto3" json:"U64,omitempty"`
	Bool bool   `protobuf:"varint,5,opt,name=Bool,proto3" json:"Bool,omitempty"`
	Str  string `protobuf:"bytes,6,opt,name=Str,proto3" json:"Str,omitempty"`
}

func (x *Simple) Reset() {
	*x = Simple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Simple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simple) ProtoMessage() {}

func (x *Simple) ProtoReflect() protoreflect.Message {
	mi := &file_seq_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simple.ProtoReflect.Descriptor instead.
func (*Simple) Descriptor() ([]byte, []int) {
	return file_seq_test_proto_rawDescGZIP(), []int{1}
}

func (x *Simple) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *Simple) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Simple) GetU32() uint32 {
	if x != nil {
		return x.U32
	}
	return 0
}

func (x *Simple) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

func (x *Simple) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Simple) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type Lists struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Len     []int32   `protobuf:"varint,1,rep,packed,name=Len,proto3" json:"Len,omitempty"`
	Missing []int32   `protobuf:"varint,2,rep,packed,name=Missing,proto3" json:"Missing,omitempty"`
	Mistake []*Simple `protobuf:"bytes,4,rep,name=Mistake,proto3" json:"Mistake,omitempty"`
}

func (x *Lists) Reset() {
	*x = Lists{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lists) ProtoMessage() {}

func (x *Lists) ProtoReflect() protoreflect.Message {
	mi := &file_seq_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lists.ProtoReflect.Descriptor instead.
func (*Lists) Descriptor() ([]byte, []int) {
	return file_seq_test_proto_rawDescGZIP(), []int{2}
}

func (x *Lists) GetLen() []int32 {
	if x != nil {
		return x.Len
	}
	return nil
}

func (x *Lists) GetMissing() []int32 {
	if x != nil {
		return x.Missing
	}
	return nil
}

func (x *Lists) GetMistake() []*Simple {
	if x != nil {
		return x.Mistake
	}
	return nil
}

type Nested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nested) Reset() {
	*x = Nested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_seq_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_seq_test_proto_rawDescGZIP(), []int{3}
}

var File_seq_test_proto protoreflect.FileDescriptor

var file_seq_test_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x71, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x73, 0x65, 0x71, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x76,
	0x0a, 0x06, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x33, 0x32, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x49, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x36,
	0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x49, 0x36, 0x34, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x33, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x55, 0x33, 0x32, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x36, 0x34,
	0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x74, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x53, 0x74, 0x72, 0x22, 0x5a, 0x0a, 0x05, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x4c, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x4c, 0x65,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x07, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x25, 0x0a, 0x07, 0x4d,
	0x69, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73,
	0x65, 0x71, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x4d, 0x69, 0x73, 0x74, 0x61,
	0x6b, 0x65, 0x22, 0x08, 0x0a, 0x06, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x0d, 0x5a, 0x0b,
	0x67, 0x6f, 0x2d, 0x6c, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_seq_test_proto_rawDescOnce sync.Once
	file_seq_test_proto_rawDescData = file_seq_test_proto_rawDesc
)

func file_seq_test_proto_rawDescGZIP() []byte {
	file_seq_test_proto_rawDescOnce.Do(func() {
		file_seq_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_seq_test_proto_rawDescData)
	})
	return file_seq_test_proto_rawDescData
}

var file_seq_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_seq_test_proto_goTypes = []interface{}{
	(*Empty)(nil),  // 0: seq.Empty
	(*Simple)(nil), // 1: seq.Simple
	(*Lists)(nil),  // 2: seq.Lists
	(*Nested)(nil), // 3: seq.Nested
}
var file_seq_test_proto_depIdxs = []int32{
	1, // 0: seq.Lists.Mistake:type_name -> seq.Simple
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_seq_test_proto_init() }
func file_seq_test_proto_init() {
	if File_seq_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seq_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Simple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lists); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seq_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seq_test_proto_goTypes,
		DependencyIndexes: file_seq_test_proto_depIdxs,
		MessageInfos:      file_seq_test_proto_msgTypes,
	}.Build()
	File_seq_test_proto = out.File
	file_seq_test_proto_rawDesc = nil
	file_seq_test_proto_goTypes = nil
	file_seq_test_proto_depIdxs = nil
}
