// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: protos/ch1.proto

//import "google/protobuf/any.proto";

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLocationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *AddLocationsReq) Reset() {
	*x = AddLocationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLocationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocationsReq) ProtoMessage() {}

func (x *AddLocationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocationsReq.ProtoReflect.Descriptor instead.
func (*AddLocationsReq) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{0}
}

func (x *AddLocationsReq) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type AddLocationsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *AddLocationsResp) Reset() {
	*x = AddLocationsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLocationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLocationsResp) ProtoMessage() {}

func (x *AddLocationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLocationsResp.ProtoReflect.Descriptor instead.
func (*AddLocationsResp) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{1}
}

func (x *AddLocationsResp) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type LocationAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LocationAdded) Reset() {
	*x = LocationAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationAdded) ProtoMessage() {}

func (x *LocationAdded) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationAdded.ProtoReflect.Descriptor instead.
func (*LocationAdded) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{2}
}

func (x *LocationAdded) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LocationAdded) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddProductsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skus []string `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
}

func (x *AddProductsReq) Reset() {
	*x = AddProductsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsReq) ProtoMessage() {}

func (x *AddProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsReq.ProtoReflect.Descriptor instead.
func (*AddProductsReq) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{3}
}

func (x *AddProductsReq) GetSkus() []string {
	if x != nil {
		return x.Skus
	}
	return nil
}

type AddProductsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *AddProductsResp) Reset() {
	*x = AddProductsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsResp) ProtoMessage() {}

func (x *AddProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsResp.ProtoReflect.Descriptor instead.
func (*AddProductsResp) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{4}
}

func (x *AddProductsResp) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ProductAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
}

func (x *ProductAdded) Reset() {
	*x = ProductAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAdded) ProtoMessage() {}

func (x *ProductAdded) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAdded.ProtoReflect.Descriptor instead.
func (*ProductAdded) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{5}
}

func (x *ProductAdded) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductAdded) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type UpdateQtyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location uint64 `protobuf:"varint,1,opt,name=location,proto3" json:"location,omitempty"`
	Product  uint64 `protobuf:"varint,2,opt,name=product,proto3" json:"product,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *UpdateQtyReq) Reset() {
	*x = UpdateQtyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQtyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQtyReq) ProtoMessage() {}

func (x *UpdateQtyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQtyReq.ProtoReflect.Descriptor instead.
func (*UpdateQtyReq) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateQtyReq) GetLocation() uint64 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *UpdateQtyReq) GetProduct() uint64 {
	if x != nil {
		return x.Product
	}
	return 0
}

func (x *UpdateQtyReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateQtyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *UpdateQtyResp) Reset() {
	*x = UpdateQtyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQtyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQtyResp) ProtoMessage() {}

func (x *UpdateQtyResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQtyResp.ProtoReflect.Descriptor instead.
func (*UpdateQtyResp) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateQtyResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type QuantityUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location uint64 `protobuf:"varint,1,opt,name=location,proto3" json:"location,omitempty"`
	Product  uint64 `protobuf:"varint,2,opt,name=product,proto3" json:"product,omitempty"`
	Quantity int64  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Total    int64  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QuantityUpdated) Reset() {
	*x = QuantityUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantityUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantityUpdated) ProtoMessage() {}

func (x *QuantityUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantityUpdated.ProtoReflect.Descriptor instead.
func (*QuantityUpdated) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{8}
}

func (x *QuantityUpdated) GetLocation() uint64 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *QuantityUpdated) GetProduct() uint64 {
	if x != nil {
		return x.Product
	}
	return 0
}

func (x *QuantityUpdated) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *QuantityUpdated) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListLocationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location uint64 `protobuf:"varint,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *ListLocationsRequest) Reset() {
	*x = ListLocationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsRequest) ProtoMessage() {}

func (x *ListLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{9}
}

func (x *ListLocationsRequest) GetLocation() uint64 {
	if x != nil {
		return x.Location
	}
	return 0
}

type ListLocationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListLocationsResponse) Reset() {
	*x = ListLocationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResponse) ProtoMessage() {}

func (x *ListLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{10}
}

type GetInventoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location uint64 `protobuf:"varint,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetInventoryReq) Reset() {
	*x = GetInventoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryReq) ProtoMessage() {}

func (x *GetInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryReq.ProtoReflect.Descriptor instead.
func (*GetInventoryReq) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{11}
}

func (x *GetInventoryReq) GetLocation() uint64 {
	if x != nil {
		return x.Location
	}
	return 0
}

type GetInventoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GetInventoryResp_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetInventoryResp) Reset() {
	*x = GetInventoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResp) ProtoMessage() {}

func (x *GetInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResp.ProtoReflect.Descriptor instead.
func (*GetInventoryResp) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{12}
}

func (x *GetInventoryResp) GetItems() []*GetInventoryResp_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListLocationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListLocationsReq) Reset() {
	*x = ListLocationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLocationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsReq) ProtoMessage() {}

func (x *ListLocationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsReq.ProtoReflect.Descriptor instead.
func (*ListLocationsReq) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{13}
}

type ListLocationsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locs []*ListLocationsResp_Loc `protobuf:"bytes,1,rep,name=locs,proto3" json:"locs,omitempty"`
}

func (x *ListLocationsResp) Reset() {
	*x = ListLocationsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLocationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResp) ProtoMessage() {}

func (x *ListLocationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResp.ProtoReflect.Descriptor instead.
func (*ListLocationsResp) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{14}
}

func (x *ListLocationsResp) GetLocs() []*ListLocationsResp_Loc {
	if x != nil {
		return x.Locs
	}
	return nil
}

type GetInventoryResp_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product  uint64 `protobuf:"varint,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *GetInventoryResp_Item) Reset() {
	*x = GetInventoryResp_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInventoryResp_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResp_Item) ProtoMessage() {}

func (x *GetInventoryResp_Item) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResp_Item.ProtoReflect.Descriptor instead.
func (*GetInventoryResp_Item) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{12, 0}
}

func (x *GetInventoryResp_Item) GetProduct() uint64 {
	if x != nil {
		return x.Product
	}
	return 0
}

func (x *GetInventoryResp_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ListLocationsResp_Loc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListLocationsResp_Loc) Reset() {
	*x = ListLocationsResp_Loc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ch1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLocationsResp_Loc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResp_Loc) ProtoMessage() {}

func (x *ListLocationsResp_Loc) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ch1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResp_Loc.ProtoReflect.Descriptor instead.
func (*ListLocationsResp_Loc) Descriptor() ([]byte, []int) {
	return file_protos_ch1_proto_rawDescGZIP(), []int{14, 0}
}

func (x *ListLocationsResp_Loc) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListLocationsResp_Loc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protos_ch1_proto protoreflect.FileDescriptor

var file_protos_ch1_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x68, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x27, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x33, 0x0a, 0x0d, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24,
	0x0a, 0x0e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x6b, 0x75, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x22, 0x60, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x25, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0x79, 0x0a, 0x0f, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x32, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x33, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x3c, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x22, 0x71, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x04,
	0x6c, 0x6f, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4c, 0x6f, 0x63, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x73, 0x1a,
	0x29, 0x0a, 0x03, 0x4c, 0x6f, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xd8, 0x02, 0x0a, 0x10, 0x49,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x41, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x44, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x51, 0x74, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x6f, 0x2d, 0x6c, 0x69, 0x74, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_ch1_proto_rawDescOnce sync.Once
	file_protos_ch1_proto_rawDescData = file_protos_ch1_proto_rawDesc
)

func file_protos_ch1_proto_rawDescGZIP() []byte {
	file_protos_ch1_proto_rawDescOnce.Do(func() {
		file_protos_ch1_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_ch1_proto_rawDescData)
	})
	return file_protos_ch1_proto_rawDescData
}

var file_protos_ch1_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protos_ch1_proto_goTypes = []interface{}{
	(*AddLocationsReq)(nil),       // 0: protos.AddLocationsReq
	(*AddLocationsResp)(nil),      // 1: protos.AddLocationsResp
	(*LocationAdded)(nil),         // 2: protos.LocationAdded
	(*AddProductsReq)(nil),        // 3: protos.AddProductsReq
	(*AddProductsResp)(nil),       // 4: protos.AddProductsResp
	(*ProductAdded)(nil),          // 5: protos.ProductAdded
	(*UpdateQtyReq)(nil),          // 6: protos.UpdateQtyReq
	(*UpdateQtyResp)(nil),         // 7: protos.UpdateQtyResp
	(*QuantityUpdated)(nil),       // 8: protos.QuantityUpdated
	(*ListLocationsRequest)(nil),  // 9: protos.ListLocationsRequest
	(*ListLocationsResponse)(nil), // 10: protos.ListLocationsResponse
	(*GetInventoryReq)(nil),       // 11: protos.GetInventoryReq
	(*GetInventoryResp)(nil),      // 12: protos.GetInventoryResp
	(*ListLocationsReq)(nil),      // 13: protos.ListLocationsReq
	(*ListLocationsResp)(nil),     // 14: protos.ListLocationsResp
	(*GetInventoryResp_Item)(nil), // 15: protos.GetInventoryResp.Item
	(*ListLocationsResp_Loc)(nil), // 16: protos.ListLocationsResp.Loc
}
var file_protos_ch1_proto_depIdxs = []int32{
	15, // 0: protos.GetInventoryResp.items:type_name -> protos.GetInventoryResp.Item
	16, // 1: protos.ListLocationsResp.locs:type_name -> protos.ListLocationsResp.Loc
	0,  // 2: protos.InventoryService.AddLocations:input_type -> protos.AddLocationsReq
	3,  // 3: protos.InventoryService.AddProducts:input_type -> protos.AddProductsReq
	13, // 4: protos.InventoryService.ListLocations:input_type -> protos.ListLocationsReq
	6,  // 5: protos.InventoryService.UpdateQty:input_type -> protos.UpdateQtyReq
	11, // 6: protos.InventoryService.GetInventory:input_type -> protos.GetInventoryReq
	1,  // 7: protos.InventoryService.AddLocations:output_type -> protos.AddLocationsResp
	4,  // 8: protos.InventoryService.AddProducts:output_type -> protos.AddProductsResp
	14, // 9: protos.InventoryService.ListLocations:output_type -> protos.ListLocationsResp
	7,  // 10: protos.InventoryService.UpdateQty:output_type -> protos.UpdateQtyResp
	12, // 11: protos.InventoryService.GetInventory:output_type -> protos.GetInventoryResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protos_ch1_proto_init() }
func file_protos_ch1_proto_init() {
	if File_protos_ch1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_ch1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLocationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLocationsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQtyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQtyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantityUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLocationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLocationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInventoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInventoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLocationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLocationsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInventoryResp_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ch1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLocationsResp_Loc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_ch1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ch1_proto_goTypes,
		DependencyIndexes: file_protos_ch1_proto_depIdxs,
		MessageInfos:      file_protos_ch1_proto_msgTypes,
	}.Build()
	File_protos_ch1_proto = out.File
	file_protos_ch1_proto_rawDesc = nil
	file_protos_ch1_proto_goTypes = nil
	file_protos_ch1_proto_depIdxs = nil
}
