# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ch1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tch1.proto\x12\x06protos\x1a\x19google/protobuf/any.proto\"\"\n\x12\x41\x64\x64LocationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x13\x41\x64\x64LocationResponse\x12\n\n\x02id\x18\x02 \x01(\x04\")\n\rLocationAdded\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x04\"!\n\x11\x41\x64\x64ProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x12\x41\x64\x64ProductResponse\x12\n\n\x02id\x18\x02 \x01(\x04\"(\n\x0cProductAdded\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\"L\n\x15\x43hangeQuantityRequest\x12\x10\n\x08location\x18\x01 \x01(\x04\x12\x0f\n\x07product\x18\x02 \x01(\x04\x12\x10\n\x08quantity\x18\x03 \x01(\x04\"U\n\x0fQuantityChanged\x12\x10\n\x08location\x18\x01 \x01(\x04\x12\x0f\n\x07product\x18\x02 \x01(\x04\x12\x10\n\x08quantity\x18\x03 \x01(\x04\x12\r\n\x05total\x18\x04 \x01(\x04\"\'\n\x16\x43hangeQuantityResponse\x12\r\n\x05total\x18\x01 \x01(\x04\"\'\n\x13ListLocationRequest\x12\x10\n\x08location\x18\x01 \x01(\x04\"s\n\x14ListLocationResponse\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32!.protos.ListLocationResponse.Item\x1a)\n\x04Item\x12\x0f\n\x07product\x18\x01 \x01(\x04\x12\x10\n\x08quantity\x18\x02 \x01(\x04\"5\n\rRewindRequest\x12$\n\x06\x45vents\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"\x10\n\x0eRewindResponse\"\n\n\x08TestCase2\xbb\x02\n\x10InventoryService\x12\x46\n\x0b\x41\x64\x64Location\x12\x1a.protos.AddLocationRequest\x1a\x1b.protos.AddLocationResponse\x12\x43\n\nAddProduct\x12\x19.protos.AddProductRequest\x1a\x1a.protos.AddProductResponse\x12O\n\x0e\x43hangeQuantity\x12\x1d.protos.ChangeQuantityRequest\x1a\x1e.protos.ChangeQuantityResponse\x12I\n\x0cListLocation\x12\x1b.protos.ListLocationRequest\x1a\x1c.protos.ListLocationResponseB\x10Z\x0ego-lite/protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ch1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016go-lite/protos'
  _ADDLOCATIONREQUEST._serialized_start=48
  _ADDLOCATIONREQUEST._serialized_end=82
  _ADDLOCATIONRESPONSE._serialized_start=84
  _ADDLOCATIONRESPONSE._serialized_end=117
  _LOCATIONADDED._serialized_start=119
  _LOCATIONADDED._serialized_end=160
  _ADDPRODUCTREQUEST._serialized_start=162
  _ADDPRODUCTREQUEST._serialized_end=195
  _ADDPRODUCTRESPONSE._serialized_start=197
  _ADDPRODUCTRESPONSE._serialized_end=229
  _PRODUCTADDED._serialized_start=231
  _PRODUCTADDED._serialized_end=271
  _CHANGEQUANTITYREQUEST._serialized_start=273
  _CHANGEQUANTITYREQUEST._serialized_end=349
  _QUANTITYCHANGED._serialized_start=351
  _QUANTITYCHANGED._serialized_end=436
  _CHANGEQUANTITYRESPONSE._serialized_start=438
  _CHANGEQUANTITYRESPONSE._serialized_end=477
  _LISTLOCATIONREQUEST._serialized_start=479
  _LISTLOCATIONREQUEST._serialized_end=518
  _LISTLOCATIONRESPONSE._serialized_start=520
  _LISTLOCATIONRESPONSE._serialized_end=635
  _LISTLOCATIONRESPONSE_ITEM._serialized_start=594
  _LISTLOCATIONRESPONSE_ITEM._serialized_end=635
  _REWINDREQUEST._serialized_start=637
  _REWINDREQUEST._serialized_end=690
  _REWINDRESPONSE._serialized_start=692
  _REWINDRESPONSE._serialized_end=708
  _TESTCASE._serialized_start=710
  _TESTCASE._serialized_end=720
  _INVENTORYSERVICE._serialized_start=723
  _INVENTORYSERVICE._serialized_end=1038
# @@protoc_insertion_point(module_scope)
