"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
from qa import protos

class InventoryServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    AddLocation: grpc.UnaryUnaryMultiCallable[
        protos.ch1_pb2.AddLocationRequest,
        protos.ch1_pb2.AddLocationResponse,
    ]
    AddProduct: grpc.UnaryUnaryMultiCallable[
        protos.ch1_pb2.AddProductRequest,
        protos.ch1_pb2.AddProductResponse,
    ]
    ChangeQuantity: grpc.UnaryUnaryMultiCallable[
        protos.ch1_pb2.ChangeQuantityRequest,
        protos.ch1_pb2.ChangeQuantityResponse,
    ]
    ListLocation: grpc.UnaryUnaryMultiCallable[
        protos.ch1_pb2.ListLocationRequest,
        protos.ch1_pb2.ListLocationResponse,
    ]

class InventoryServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def AddLocation(
        self,
        request: protos.ch1_pb2.AddLocationRequest,
        context: grpc.ServicerContext,
    ) -> protos.ch1_pb2.AddLocationResponse: ...
    @abc.abstractmethod
    def AddProduct(
        self,
        request: protos.ch1_pb2.AddProductRequest,
        context: grpc.ServicerContext,
    ) -> protos.ch1_pb2.AddProductResponse: ...
    @abc.abstractmethod
    def ChangeQuantity(
        self,
        request: protos.ch1_pb2.ChangeQuantityRequest,
        context: grpc.ServicerContext,
    ) -> protos.ch1_pb2.ChangeQuantityResponse: ...
    @abc.abstractmethod
    def ListLocation(
        self,
        request: protos.ch1_pb2.ListLocationRequest,
        context: grpc.ServicerContext,
    ) -> protos.ch1_pb2.ListLocationResponse: ...

def add_InventoryServiceServicer_to_server(servicer: InventoryServiceServicer, server: grpc.Server) -> None: ...
